services:
  traefik:
    container_name: traefik
    image: traefik:3.7
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    networks:
      traefik:
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/.acme.sh/${DOMAIN}_ecc:/certs:ro
      - ./traefik:/etc/traefik:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=80"

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    networks:
      traefik:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dozzle_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.${DOMAIN}`)"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.routers.dozzle.tls=true"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    networks:
      lan:
        gw_priority: 1
        ipv4_address: 192.168.69.241
      traefik:
    volumes:
      - /var/run/dbus:/var/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
      - ~/.homeassistant:/config
    environment:
      TZ: America/New_York
    cap_add:
      - NET_ADMIN
      - NET_RAW
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.${DOMAIN}`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls=true"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf -H \"Authorization: Bearer ${HOMEASSISTANT_TOKEN}\" http://localhost:8123/api/config | jq '.state == \"RUNNING\"' || exit 1"]

  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    networks:
      lan:
        gw_priority: 1
        ipv4_address: 192.168.69.242
      traefik:
    volumes:
      - homebridge_homebridge:/homebridge
    environment:
      TZ: America/New_York
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homebridge.rule=Host(`homebridge.${DOMAIN}`)"
      - "traefik.http.routers.homebridge.entrypoints=websecure"
      - "traefik.http.routers.homebridge.tls=true"
      - "traefik.http.services.homebridge.loadbalancer.server.port=8581"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf -H \"Authorization: Bearer ${HOMEBRIDGE_TOKEN}\" http://localhost:8581/api/status/homebridge | jq '.status == \"ok\"' || exit 1"]

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    networks:
      traefik:
    ports:
      - 53:53/tcp
      - 53:53/udp
    dns:
      - 127.0.0.1
      - 9.9.9.9
      - 149.112.112.112
      - 2620:fe::9
      - 2620:fe::fe
    volumes:
      - pihole_etc_pihole:/etc/pihole/
    env_file: ./pihole.env
    cap_add:
      - SYS_TIME
      - SYS_NICE
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${DOMAIN}`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    security_opt:
      - no-new-privileges
    networks:
      traefik:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  whoami:
    container_name: whoami
    image: traefik/whoami
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    networks:
      traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"

networks:
  traefik:
    name: traefik
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
        - subnet: fd27:1105:6dac::/64
          gateway: fd27:1105:6dac::1
  lan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.69.0/24
          gateway: 192.168.69.1
          ip_range: 192.168.69.240/28

volumes:
  dozzle_data:
  homebridge_homebridge:
  pihole_etc_pihole:
  portainer_data:
